#!/bin/bash

set -e

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = ${TheSkyX_Install}"

if [ ! -f "${TheSkyX_Install}" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"${TheSkyX_Install}")
echo "Installing to ${TheSkyX_Path}"

if [ ! -d "${TheSkyX_Path}" ]; then
    echo TheSkyX Install dir not exist
    exit 1
fi


cp "/tmp/QhyCfw3Usb_X2/filterwheellist QHYCFW3.txt" "${TheSkyX_Path}/Resources/Common/Miscellaneous Files/"
cp "/tmp/QhyCfw3Usb_X2/libqhycfw3_usb.dylib" "${TheSkyX_Path}/PlugIns/FilterWheelPlugIns"
cp "/tmp/QhyCfw3Usb_X2/qhycfw3_usb.ui" "${TheSkyX_Path}/PlugIns/FilterWheelPlugIns"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
    chown $app_owner "${TheSkyX_Path}/Resources/Common/Miscellaneous Files/filterwheellist QHYCFW3.txt"
    chown $app_owner "${TheSkyX_Path}/PlugIns/FilterWheelPlugIns/libqhycfw3_usb.dylib"
        chown $app_owner "${TheSkyX_Path}/PlugIns/FilterWheelPlugIns/qhycfw3_usb.ui"
fi

rm -rf /tmp/QhyCfw3Usb_X2
